version: '3.8'

services:
  excel-processor:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      platforms:
        - linux/amd64
        - linux/arm64
    image: excel-processor:latest
    container_name: excel-processor-app
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    
    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    
    # 环境变量
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    
    # 标签
    labels:
      - "com.excel-processor.description=Excel文件处理工具"
      - "com.excel-processor.version=1.0.0"
      - "com.excel-processor.architecture=multi"

  # 可选：添加反向代理（用于生产环境）
  nginx-proxy:
    image: nginx:alpine
    container_name: excel-processor-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - excel-processor
    restart: unless-stopped
    profiles:
      - proxy

networks:
  default:
    name: excel-processor-network
    driver: bridge

volumes:
  nginx-cache:
    driver: local
    labels:
      - "com.excel-processor.volume=cache"