name: Deploy to Cloudflare Pages (Wrangler)

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages deploy ./ --project-name=excel-processor
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'